<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="catalogo">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="libro" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="titulo"  type="xs:string"/>
              <xs:element name="autor"   type="xs:string"/>
              <xs:element name="ano"     type="xs:integer"/>
              <xs:element name="genero"  type="xs:string"/>
              <xs:element name="precio">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:decimal">
                      <xs:attribute name="moneda" type="xs:string" use="required"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="stock" type="xs:nonNegativeInteger"/>
            </xs:sequence>
            <xs:attribute name="id"         type="xs:string"  use="required"/>
            <xs:attribute name="disponible" type="xs:boolean" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="version"        type="xs:string"/>
      <xs:attribute name="fecha_creacion" type="xs:string"/>
    </xs:complexType>
  </xs:element>

</xs:schema>
